/*
 * Generated by Bluespec Compiler
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbAccelerator.h"


/* String declarations */
static std::string const __str_literal_7("  output[0] = %0d (expect 23)", 29u);
static std::string const __str_literal_8("  output[1] = %0d (expect 34)", 29u);
static std::string const __str_literal_3("Cycle %0d: activations loaded to SRAM", 37u);
static std::string const __str_literal_6("Cycle %0d: compute done", 23u);
static std::string const __str_literal_4("Cycle %0d: compute started", 26u);
static std::string const __str_literal_5("Cycle %0d: computing...", 23u);
static std::string const __str_literal_2("Cycle %0d: weights loaded to SRAM", 33u);
static std::string const __str_literal_1("FAIL: test timed out at cycle %0d", 33u);
static std::string const __str_literal_10("FAIL: unexpected output", 23u);
static std::string const __str_literal_9("PASS: full accelerator test", 27u);


/* Constructor */
MOD_mkTbAccelerator::MOD_mkTbAccelerator(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_accel_aSRAM_mem(simHdl, "accel_aSRAM_mem", this, 2u, 16u, (tUInt8)0u, (tUInt8)3u),
    INST_accel_aSRAM_resp(simHdl, "accel_aSRAM_resp", this, 16u),
    INST_accel_array_pes_0_0_accum(simHdl, "accel_array_pes_0_0_accum", this, 32u, 0u, (tUInt8)0u),
    INST_accel_array_pes_0_0_act_pass(simHdl,
				      "accel_array_pes_0_0_act_pass",
				      this,
				      8u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_accel_array_pes_0_0_weight(simHdl,
				    "accel_array_pes_0_0_weight",
				    this,
				    8u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_accel_array_pes_0_1_accum(simHdl, "accel_array_pes_0_1_accum", this, 32u, 0u, (tUInt8)0u),
    INST_accel_array_pes_0_1_act_pass(simHdl,
				      "accel_array_pes_0_1_act_pass",
				      this,
				      8u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_accel_array_pes_0_1_weight(simHdl,
				    "accel_array_pes_0_1_weight",
				    this,
				    8u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_accel_array_pes_1_0_accum(simHdl, "accel_array_pes_1_0_accum", this, 32u, 0u, (tUInt8)0u),
    INST_accel_array_pes_1_0_act_pass(simHdl,
				      "accel_array_pes_1_0_act_pass",
				      this,
				      8u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_accel_array_pes_1_0_weight(simHdl,
				    "accel_array_pes_1_0_weight",
				    this,
				    8u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_accel_array_pes_1_1_accum(simHdl, "accel_array_pes_1_1_accum", this, 32u, 0u, (tUInt8)0u),
    INST_accel_array_pes_1_1_act_pass(simHdl,
				      "accel_array_pes_1_1_act_pass",
				      this,
				      8u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_accel_array_pes_1_1_weight(simHdl,
				    "accel_array_pes_1_1_weight",
				    this,
				    8u,
				    (tUInt8)0u,
				    (tUInt8)0u),
    INST_accel_ctrl_aBase(simHdl, "accel_ctrl_aBase", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_accel_ctrl_actIdx(simHdl, "accel_ctrl_actIdx", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_accel_ctrl_cstate(simHdl, "accel_ctrl_cstate", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_accel_ctrl_firstActRead(simHdl, "accel_ctrl_firstActRead", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_accel_ctrl_outputBuf(simHdl, "accel_ctrl_outputBuf", this, 64u),
    INST_accel_ctrl_streamCycle(simHdl, "accel_ctrl_streamCycle", this, 32u, 0u, (tUInt8)0u),
    INST_accel_ctrl_tLen(simHdl, "accel_ctrl_tLen", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_accel_ctrl_wBase(simHdl, "accel_ctrl_wBase", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_accel_wSRAM_mem(simHdl, "accel_wSRAM_mem", this, 2u, 32u, (tUInt8)0u, (tUInt8)3u),
    INST_accel_wSRAM_resp(simHdl, "accel_wSRAM_resp", this, 32u),
    INST_cycle(simHdl, "cycle", this, 8u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 36u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbAccelerator::init_symbols_0()
{
  init_symbol(&symbols[0u], "accel_array_pes_0_0_accum", SYM_MODULE, &INST_accel_array_pes_0_0_accum);
  init_symbol(&symbols[1u],
	      "accel_array_pes_0_0_act_pass",
	      SYM_MODULE,
	      &INST_accel_array_pes_0_0_act_pass);
  init_symbol(&symbols[2u],
	      "accel_array_pes_0_0_weight",
	      SYM_MODULE,
	      &INST_accel_array_pes_0_0_weight);
  init_symbol(&symbols[3u], "accel_array_pes_0_1_accum", SYM_MODULE, &INST_accel_array_pes_0_1_accum);
  init_symbol(&symbols[4u],
	      "accel_array_pes_0_1_act_pass",
	      SYM_MODULE,
	      &INST_accel_array_pes_0_1_act_pass);
  init_symbol(&symbols[5u],
	      "accel_array_pes_0_1_weight",
	      SYM_MODULE,
	      &INST_accel_array_pes_0_1_weight);
  init_symbol(&symbols[6u], "accel_array_pes_1_0_accum", SYM_MODULE, &INST_accel_array_pes_1_0_accum);
  init_symbol(&symbols[7u],
	      "accel_array_pes_1_0_act_pass",
	      SYM_MODULE,
	      &INST_accel_array_pes_1_0_act_pass);
  init_symbol(&symbols[8u],
	      "accel_array_pes_1_0_weight",
	      SYM_MODULE,
	      &INST_accel_array_pes_1_0_weight);
  init_symbol(&symbols[9u], "accel_array_pes_1_1_accum", SYM_MODULE, &INST_accel_array_pes_1_1_accum);
  init_symbol(&symbols[10u],
	      "accel_array_pes_1_1_act_pass",
	      SYM_MODULE,
	      &INST_accel_array_pes_1_1_act_pass);
  init_symbol(&symbols[11u],
	      "accel_array_pes_1_1_weight",
	      SYM_MODULE,
	      &INST_accel_array_pes_1_1_weight);
  init_symbol(&symbols[12u], "accel_aSRAM_mem", SYM_MODULE, &INST_accel_aSRAM_mem);
  init_symbol(&symbols[13u], "accel_aSRAM_resp", SYM_MODULE, &INST_accel_aSRAM_resp);
  init_symbol(&symbols[14u], "accel_ctrl_aBase", SYM_MODULE, &INST_accel_ctrl_aBase);
  init_symbol(&symbols[15u], "accel_ctrl_actIdx", SYM_MODULE, &INST_accel_ctrl_actIdx);
  init_symbol(&symbols[16u], "accel_ctrl_cstate", SYM_MODULE, &INST_accel_ctrl_cstate);
  init_symbol(&symbols[17u], "accel_ctrl_firstActRead", SYM_MODULE, &INST_accel_ctrl_firstActRead);
  init_symbol(&symbols[18u], "accel_ctrl_outputBuf", SYM_MODULE, &INST_accel_ctrl_outputBuf);
  init_symbol(&symbols[19u], "accel_ctrl_streamCycle", SYM_MODULE, &INST_accel_ctrl_streamCycle);
  init_symbol(&symbols[20u], "accel_ctrl_tLen", SYM_MODULE, &INST_accel_ctrl_tLen);
  init_symbol(&symbols[21u], "accel_ctrl_wBase", SYM_MODULE, &INST_accel_ctrl_wBase);
  init_symbol(&symbols[22u], "accel_wSRAM_mem", SYM_MODULE, &INST_accel_wSRAM_mem);
  init_symbol(&symbols[23u], "accel_wSRAM_resp", SYM_MODULE, &INST_accel_wSRAM_resp);
  init_symbol(&symbols[24u], "b__h6314", SYM_DEF, &DEF_b__h6314, 8u);
  init_symbol(&symbols[25u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[26u], "RL_accel_ctrl_do_drain", SYM_RULE);
  init_symbol(&symbols[27u], "RL_accel_ctrl_do_load_weights", SYM_RULE);
  init_symbol(&symbols[28u], "RL_accel_ctrl_do_load_weights_resp", SYM_RULE);
  init_symbol(&symbols[29u], "RL_accel_ctrl_do_stream", SYM_RULE);
  init_symbol(&symbols[30u], "RL_check_done", SYM_RULE);
  init_symbol(&symbols[31u], "RL_count_cycles", SYM_RULE);
  init_symbol(&symbols[32u], "RL_load_acts", SYM_RULE);
  init_symbol(&symbols[33u], "RL_load_weights", SYM_RULE);
  init_symbol(&symbols[34u], "RL_start", SYM_RULE);
  init_symbol(&symbols[35u], "RL_wait_done", SYM_RULE);
}


/* Rule actions */

void MOD_mkTbAccelerator::RL_accel_ctrl_do_load_weights()
{
  tUInt8 DEF_b__h1910;
  tUInt32 DEF_accel_wSRAM_mem_sub_accel_ctrl_wBase___d4;
  DEF_b__h1910 = INST_accel_ctrl_wBase.METH_read();
  DEF_accel_wSRAM_mem_sub_accel_ctrl_wBase___d4 = INST_accel_wSRAM_mem.METH_sub(DEF_b__h1910);
  INST_accel_wSRAM_resp.METH_write(DEF_accel_wSRAM_mem_sub_accel_ctrl_wBase___d4);
  INST_accel_ctrl_cstate.METH_write((tUInt8)2u);
}

void MOD_mkTbAccelerator::RL_accel_ctrl_do_load_weights_resp()
{
  tUInt8 DEF_v__h2643;
  tUInt8 DEF_v__h2648;
  tUInt8 DEF_v__h3007;
  tUInt8 DEF_v__h3012;
  tUInt32 DEF_accel_aSRAM_mem_sub_accel_ctrl_aBase_1___d12;
  tUInt32 DEF_accel_wSRAM_resp__h3083;
  DEF_accel_wSRAM_resp__h3083 = INST_accel_wSRAM_resp.METH_read();
  DEF_b__h3447 = INST_accel_ctrl_aBase.METH_read();
  DEF_accel_aSRAM_mem_sub_accel_ctrl_aBase_1___d12 = INST_accel_aSRAM_mem.METH_sub(DEF_b__h3447);
  DEF_v__h3012 = (tUInt8)(DEF_accel_wSRAM_resp__h3083 >> 24u);
  DEF_v__h3007 = (tUInt8)((tUInt8)255u & (DEF_accel_wSRAM_resp__h3083 >> 16u));
  DEF_v__h2648 = (tUInt8)((tUInt8)255u & (DEF_accel_wSRAM_resp__h3083 >> 8u));
  DEF_v__h2643 = (tUInt8)((tUInt8)255u & DEF_accel_wSRAM_resp__h3083);
  INST_accel_array_pes_0_0_weight.METH_write(DEF_v__h2643);
  INST_accel_array_pes_0_1_weight.METH_write(DEF_v__h2648);
  INST_accel_array_pes_1_0_weight.METH_write(DEF_v__h3007);
  INST_accel_array_pes_1_1_weight.METH_write(DEF_v__h3012);
  INST_accel_aSRAM_resp.METH_write(DEF_accel_aSRAM_mem_sub_accel_ctrl_aBase_1___d12);
  INST_accel_ctrl_actIdx.METH_write((tUInt8)1u);
  INST_accel_ctrl_streamCycle.METH_write(0u);
  INST_accel_ctrl_firstActRead.METH_write((tUInt8)1u);
  INST_accel_ctrl_cstate.METH_write((tUInt8)3u);
}

void MOD_mkTbAccelerator::RL_accel_ctrl_do_stream()
{
  tUInt8 DEF_accel_ctrl_actIdx_8_PLUS_1___d63;
  tUInt32 DEF_accel_ctrl_streamCycle_4_PLUS_1___d64;
  tUInt32 DEF_accel_array_pes_0_1_accum_2_PLUS_SEXT_accel_ar_ETC___d39;
  tUInt32 DEF_accel_array_pes_1_1_accum_0_PLUS_SEXT_accel_ar_ETC___d57;
  tUInt8 DEF_NOT_accel_ctrl_streamCycle_4_ULT_0_CONCAT_acce_ETC___d65;
  tUInt8 DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19;
  tUInt8 DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d60;
  tUInt32 DEF__0_CONCAT_accel_ctrl_tLen_5___d16;
  tUInt8 DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d31;
  tUInt8 DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d49;
  tUInt32 DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d48;
  tUInt8 DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d20;
  tUInt32 DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d30;
  tUInt8 DEF_v__h3838;
  tUInt8 DEF_v__h3843;
  tUInt8 DEF_b__h3665;
  tUInt8 DEF_b__h5068;
  tUInt8 DEF_b__h3897;
  tUInt8 DEF_b__h4034;
  tUInt8 DEF_b__h4038;
  tUInt8 DEF_b__h4200;
  tUInt8 DEF_b__h4337;
  tUInt8 DEF_b__h4341;
  tUInt32 DEF_accel_aSRAM_mem_sub_accel_ctrl_aBase_1_PLUS_ac_ETC___d62;
  tUInt32 DEF_accel_aSRAM_resp__h4196;
  tUInt32 DEF_b__h3638;
  DEF_b__h3638 = INST_accel_ctrl_streamCycle.METH_read();
  DEF_b__h4310 = INST_accel_array_pes_1_1_accum.METH_read();
  DEF_accel_array_pes_1_0_accum___d40 = INST_accel_array_pes_1_0_accum.METH_read();
  DEF_accel_array_pes_0_1_accum___d32 = INST_accel_array_pes_0_1_accum.METH_read();
  DEF_accel_aSRAM_resp__h4196 = INST_accel_aSRAM_resp.METH_read();
  DEF_accel_array_pes_0_0_accum___d21 = INST_accel_array_pes_0_0_accum.METH_read();
  DEF_b__h3447 = INST_accel_ctrl_aBase.METH_read();
  DEF_b__h4341 = INST_accel_array_pes_1_1_weight.METH_read();
  DEF_b__h4337 = INST_accel_array_pes_1_0_act_pass.METH_read();
  DEF_b__h4200 = INST_accel_array_pes_1_0_weight.METH_read();
  DEF_b__h4038 = INST_accel_array_pes_0_1_weight.METH_read();
  DEF_b__h3897 = INST_accel_array_pes_0_0_weight.METH_read();
  DEF_b__h4034 = INST_accel_array_pes_0_0_act_pass.METH_read();
  DEF_b__h5068 = INST_accel_ctrl_actIdx.METH_read();
  DEF_accel_aSRAM_mem_sub_accel_ctrl_aBase_1_PLUS_ac_ETC___d62 = INST_accel_aSRAM_mem.METH_sub((tUInt8)3u & (DEF_b__h3447 + DEF_b__h5068));
  DEF_v__h3843 = (tUInt8)(DEF_accel_aSRAM_resp__h4196 >> 8u);
  DEF_b__h3665 = INST_accel_ctrl_tLen.METH_read();
  DEF_v__h3838 = (tUInt8)((tUInt8)255u & DEF_accel_aSRAM_resp__h4196);
  DEF__0_CONCAT_accel_ctrl_tLen_5___d16 = (tUInt32)(DEF_b__h3665);
  DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d20 = DEF_b__h3638 < DEF__0_CONCAT_accel_ctrl_tLen_5___d16;
  DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d30 = DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d20 ? DEF_accel_array_pes_0_0_accum___d21 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
																									  8u,
																									  (tUInt8)(DEF_v__h3838)))) * ((tUInt64)(primSignExt32(32u,
																															       8u,
																															       (tUInt8)(DEF_b__h3897)))))) : DEF_accel_array_pes_0_0_accum___d21;
  DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d48 = DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d20 ? DEF_accel_array_pes_1_0_accum___d40 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
																									  8u,
																									  (tUInt8)(DEF_v__h3843)))) * ((tUInt64)(primSignExt32(32u,
																															       8u,
																															       (tUInt8)(DEF_b__h4200)))))) : DEF_accel_array_pes_1_0_accum___d40;
  DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d49 = DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d20 ? DEF_v__h3843 : (tUInt8)0u;
  DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d31 = DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d20 ? DEF_v__h3838 : (tUInt8)0u;
  DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19 = DEF_b__h3638 < (DEF__0_CONCAT_accel_ctrl_tLen_5___d16 + 2u) - 1u;
  DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d60 = DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19 && DEF_b__h5068 < DEF_b__h3665;
  DEF_NOT_accel_ctrl_streamCycle_4_ULT_0_CONCAT_acce_ETC___d65 = !DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19;
  DEF_accel_array_pes_1_1_accum_0_PLUS_SEXT_accel_ar_ETC___d57 = DEF_b__h4310 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
														    8u,
														    (tUInt8)(DEF_b__h4337)))) * ((tUInt64)(primSignExt32(32u,
																					 8u,
																					 (tUInt8)(DEF_b__h4341))))));
  DEF_accel_array_pes_0_1_accum_2_PLUS_SEXT_accel_ar_ETC___d39 = DEF_accel_array_pes_0_1_accum___d32 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
																	   8u,
																	   (tUInt8)(DEF_b__h4034)))) * ((tUInt64)(primSignExt32(32u,
																								8u,
																								(tUInt8)(DEF_b__h4038))))));
  DEF_accel_ctrl_streamCycle_4_PLUS_1___d64 = DEF_b__h3638 + 1u;
  DEF_accel_ctrl_actIdx_8_PLUS_1___d63 = (tUInt8)3u & (DEF_b__h5068 + (tUInt8)1u);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_0_0_accum.METH_write(DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d30);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_0_0_act_pass.METH_write(DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d31);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_0_1_accum.METH_write(DEF_accel_array_pes_0_1_accum_2_PLUS_SEXT_accel_ar_ETC___d39);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_1_0_accum.METH_write(DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d48);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_0_1_act_pass.METH_write(DEF_b__h4034);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_1_0_act_pass.METH_write(DEF_IF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ETC___d49);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_1_1_accum.METH_write(DEF_accel_array_pes_1_1_accum_0_PLUS_SEXT_accel_ar_ETC___d57);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_array_pes_1_1_act_pass.METH_write(DEF_b__h4337);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d60)
    INST_accel_aSRAM_resp.METH_write(DEF_accel_aSRAM_mem_sub_accel_ctrl_aBase_1_PLUS_ac_ETC___d62);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d60)
    INST_accel_ctrl_actIdx.METH_write(DEF_accel_ctrl_actIdx_8_PLUS_1___d63);
  if (DEF_accel_ctrl_streamCycle_4_ULT_0_CONCAT_accel_ct_ETC___d19)
    INST_accel_ctrl_streamCycle.METH_write(DEF_accel_ctrl_streamCycle_4_PLUS_1___d64);
  if (DEF_NOT_accel_ctrl_streamCycle_4_ULT_0_CONCAT_acce_ETC___d65)
    INST_accel_ctrl_cstate.METH_write((tUInt8)4u);
}

void MOD_mkTbAccelerator::RL_accel_ctrl_do_drain()
{
  tUInt64 DEF_accel_array_pes_0_1_accum_2_PLUS_accel_array_p_ETC___d69;
  DEF_b__h4310 = INST_accel_array_pes_1_1_accum.METH_read();
  DEF_accel_array_pes_1_0_accum___d40 = INST_accel_array_pes_1_0_accum.METH_read();
  DEF_accel_array_pes_0_1_accum___d32 = INST_accel_array_pes_0_1_accum.METH_read();
  DEF_accel_array_pes_0_0_accum___d21 = INST_accel_array_pes_0_0_accum.METH_read();
  DEF_accel_array_pes_0_1_accum_2_PLUS_accel_array_p_ETC___d69 = (((tUInt64)(DEF_accel_array_pes_0_1_accum___d32 + DEF_b__h4310)) << 32u) | (tUInt64)(DEF_accel_array_pes_0_0_accum___d21 + DEF_accel_array_pes_1_0_accum___d40);
  INST_accel_ctrl_outputBuf.METH_write(DEF_accel_array_pes_0_1_accum_2_PLUS_accel_array_p_ETC___d69);
  INST_accel_array_pes_0_0_accum.METH_write(0u);
  INST_accel_array_pes_0_1_accum.METH_write(0u);
  INST_accel_array_pes_1_0_accum.METH_write(0u);
  INST_accel_array_pes_1_1_accum.METH_write(0u);
  INST_accel_ctrl_cstate.METH_write((tUInt8)5u);
}

void MOD_mkTbAccelerator::RL_count_cycles()
{
  tUInt8 DEF_cycle_0_PLUS_1___d71;
  tUInt8 DEF_NOT_cycle_0_ULE_50_2___d73;
  DEF_b__h6314 = INST_cycle.METH_read();
  DEF_unsigned_cycle_0___d74 = DEF_b__h6314;
  DEF_NOT_cycle_0_ULE_50_2___d73 = !(DEF_b__h6314 <= (tUInt8)50u);
  DEF_cycle_0_PLUS_1___d71 = (tUInt8)255u & (DEF_b__h6314 + (tUInt8)1u);
  INST_cycle.METH_write(DEF_cycle_0_PLUS_1___d71);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_cycle_0_ULE_50_2___d73)
      dollar_display(sim_hdl, this, "s,8", &__str_literal_1, DEF_unsigned_cycle_0___d74);
    if (DEF_NOT_cycle_0_ULE_50_2___d73)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbAccelerator::RL_load_weights()
{
  DEF_b__h6314 = INST_cycle.METH_read();
  DEF_unsigned_cycle_0___d74 = DEF_b__h6314;
  INST_accel_wSRAM_mem.METH_upd((tUInt8)0u, 67305985u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_2, DEF_unsigned_cycle_0___d74);
}

void MOD_mkTbAccelerator::RL_load_acts()
{
  DEF_b__h6314 = INST_cycle.METH_read();
  DEF_unsigned_cycle_0___d74 = DEF_b__h6314;
  INST_accel_aSRAM_mem.METH_upd((tUInt8)0u, 1541u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_3, DEF_unsigned_cycle_0___d74);
}

void MOD_mkTbAccelerator::RL_start()
{
  DEF_b__h6314 = INST_cycle.METH_read();
  DEF_unsigned_cycle_0___d74 = DEF_b__h6314;
  INST_accel_ctrl_wBase.METH_write((tUInt8)0u);
  INST_accel_ctrl_aBase.METH_write((tUInt8)0u);
  INST_accel_ctrl_tLen.METH_write((tUInt8)1u);
  INST_accel_ctrl_actIdx.METH_write((tUInt8)0u);
  INST_accel_ctrl_streamCycle.METH_write(0u);
  INST_accel_ctrl_firstActRead.METH_write((tUInt8)0u);
  INST_accel_ctrl_cstate.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_4, DEF_unsigned_cycle_0___d74);
}

void MOD_mkTbAccelerator::RL_wait_done()
{
  DEF_b__h6314 = INST_cycle.METH_read();
  DEF_unsigned_cycle_0___d74 = DEF_b__h6314;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_5, DEF_unsigned_cycle_0___d74);
}

void MOD_mkTbAccelerator::RL_check_done()
{
  tUInt8 DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23_1__ETC___d93;
  tUInt8 DEF_NOT_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_2_ETC___d96;
  tUInt8 DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32_9_EQ_34___d92;
  tUInt8 DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23___d91;
  tUInt64 DEF_accel_ctrl_outputBuf__h7998;
  tUInt32 DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32___d89;
  tUInt32 DEF_signed_accel_ctrl_outputBuf_6_BITS_63_TO_32_9___d90;
  tUInt32 DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0___d87;
  tUInt32 DEF_signed_accel_ctrl_outputBuf_6_BITS_31_TO_0_7___d88;
  DEF_b__h6314 = INST_cycle.METH_read();
  DEF_unsigned_cycle_0___d74 = DEF_b__h6314;
  DEF_accel_ctrl_outputBuf__h7998 = INST_accel_ctrl_outputBuf.METH_read();
  DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0___d87 = (tUInt32)(DEF_accel_ctrl_outputBuf__h7998);
  DEF_signed_accel_ctrl_outputBuf_6_BITS_31_TO_0_7___d88 = DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0___d87;
  DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32___d89 = (tUInt32)(DEF_accel_ctrl_outputBuf__h7998 >> 32u);
  DEF_signed_accel_ctrl_outputBuf_6_BITS_63_TO_32_9___d90 = DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32___d89;
  DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23___d91 = DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0___d87 == 23u;
  DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32_9_EQ_34___d92 = DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32___d89 == 34u;
  DEF_NOT_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_2_ETC___d96 = !DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23___d91 || !DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32_9_EQ_34___d92;
  DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23_1__ETC___d93 = DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23___d91 && DEF_accel_ctrl_outputBuf_6_BITS_63_TO_32_9_EQ_34___d92;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s,8", &__str_literal_6, DEF_unsigned_cycle_0___d74);
    dollar_display(sim_hdl,
		   this,
		   "s,-32",
		   &__str_literal_7,
		   DEF_signed_accel_ctrl_outputBuf_6_BITS_31_TO_0_7___d88);
    dollar_display(sim_hdl,
		   this,
		   "s,-32",
		   &__str_literal_8,
		   DEF_signed_accel_ctrl_outputBuf_6_BITS_63_TO_32_9___d90);
    if (DEF_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_23_1__ETC___d93)
      dollar_display(sim_hdl, this, "s", &__str_literal_9);
    if (DEF_NOT_accel_ctrl_outputBuf_6_BITS_31_TO_0_7_EQ_2_ETC___d96)
      dollar_display(sim_hdl, this, "s", &__str_literal_10);
    dollar_finish(sim_hdl, "32", 0u);
  }
}


/* Methods */


/* Reset routines */

void MOD_mkTbAccelerator::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_cycle.reset_RST(ARG_rst_in);
  INST_accel_ctrl_wBase.reset_RST(ARG_rst_in);
  INST_accel_ctrl_tLen.reset_RST(ARG_rst_in);
  INST_accel_ctrl_streamCycle.reset_RST(ARG_rst_in);
  INST_accel_ctrl_firstActRead.reset_RST(ARG_rst_in);
  INST_accel_ctrl_cstate.reset_RST(ARG_rst_in);
  INST_accel_ctrl_actIdx.reset_RST(ARG_rst_in);
  INST_accel_ctrl_aBase.reset_RST(ARG_rst_in);
  INST_accel_array_pes_1_1_weight.reset_RST(ARG_rst_in);
  INST_accel_array_pes_1_1_act_pass.reset_RST(ARG_rst_in);
  INST_accel_array_pes_1_1_accum.reset_RST(ARG_rst_in);
  INST_accel_array_pes_1_0_weight.reset_RST(ARG_rst_in);
  INST_accel_array_pes_1_0_act_pass.reset_RST(ARG_rst_in);
  INST_accel_array_pes_1_0_accum.reset_RST(ARG_rst_in);
  INST_accel_array_pes_0_1_weight.reset_RST(ARG_rst_in);
  INST_accel_array_pes_0_1_act_pass.reset_RST(ARG_rst_in);
  INST_accel_array_pes_0_1_accum.reset_RST(ARG_rst_in);
  INST_accel_array_pes_0_0_weight.reset_RST(ARG_rst_in);
  INST_accel_array_pes_0_0_act_pass.reset_RST(ARG_rst_in);
  INST_accel_array_pes_0_0_accum.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbAccelerator::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbAccelerator::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_accel_aSRAM_mem.dump_state(indent + 2u);
  INST_accel_aSRAM_resp.dump_state(indent + 2u);
  INST_accel_array_pes_0_0_accum.dump_state(indent + 2u);
  INST_accel_array_pes_0_0_act_pass.dump_state(indent + 2u);
  INST_accel_array_pes_0_0_weight.dump_state(indent + 2u);
  INST_accel_array_pes_0_1_accum.dump_state(indent + 2u);
  INST_accel_array_pes_0_1_act_pass.dump_state(indent + 2u);
  INST_accel_array_pes_0_1_weight.dump_state(indent + 2u);
  INST_accel_array_pes_1_0_accum.dump_state(indent + 2u);
  INST_accel_array_pes_1_0_act_pass.dump_state(indent + 2u);
  INST_accel_array_pes_1_0_weight.dump_state(indent + 2u);
  INST_accel_array_pes_1_1_accum.dump_state(indent + 2u);
  INST_accel_array_pes_1_1_act_pass.dump_state(indent + 2u);
  INST_accel_array_pes_1_1_weight.dump_state(indent + 2u);
  INST_accel_ctrl_aBase.dump_state(indent + 2u);
  INST_accel_ctrl_actIdx.dump_state(indent + 2u);
  INST_accel_ctrl_cstate.dump_state(indent + 2u);
  INST_accel_ctrl_firstActRead.dump_state(indent + 2u);
  INST_accel_ctrl_outputBuf.dump_state(indent + 2u);
  INST_accel_ctrl_streamCycle.dump_state(indent + 2u);
  INST_accel_ctrl_tLen.dump_state(indent + 2u);
  INST_accel_ctrl_wBase.dump_state(indent + 2u);
  INST_accel_wSRAM_mem.dump_state(indent + 2u);
  INST_accel_wSRAM_resp.dump_state(indent + 2u);
  INST_cycle.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbAccelerator::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 33u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "accel_array_pes_0_0_accum___d21", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "accel_array_pes_0_1_accum___d32", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "accel_array_pes_1_0_accum___d40", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h3447", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h4310", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h6314", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "unsigned_cycle_0___d74", 8u);
  num = INST_accel_aSRAM_mem.dump_VCD_defs(num);
  num = INST_accel_aSRAM_resp.dump_VCD_defs(num);
  num = INST_accel_array_pes_0_0_accum.dump_VCD_defs(num);
  num = INST_accel_array_pes_0_0_act_pass.dump_VCD_defs(num);
  num = INST_accel_array_pes_0_0_weight.dump_VCD_defs(num);
  num = INST_accel_array_pes_0_1_accum.dump_VCD_defs(num);
  num = INST_accel_array_pes_0_1_act_pass.dump_VCD_defs(num);
  num = INST_accel_array_pes_0_1_weight.dump_VCD_defs(num);
  num = INST_accel_array_pes_1_0_accum.dump_VCD_defs(num);
  num = INST_accel_array_pes_1_0_act_pass.dump_VCD_defs(num);
  num = INST_accel_array_pes_1_0_weight.dump_VCD_defs(num);
  num = INST_accel_array_pes_1_1_accum.dump_VCD_defs(num);
  num = INST_accel_array_pes_1_1_act_pass.dump_VCD_defs(num);
  num = INST_accel_array_pes_1_1_weight.dump_VCD_defs(num);
  num = INST_accel_ctrl_aBase.dump_VCD_defs(num);
  num = INST_accel_ctrl_actIdx.dump_VCD_defs(num);
  num = INST_accel_ctrl_cstate.dump_VCD_defs(num);
  num = INST_accel_ctrl_firstActRead.dump_VCD_defs(num);
  num = INST_accel_ctrl_outputBuf.dump_VCD_defs(num);
  num = INST_accel_ctrl_streamCycle.dump_VCD_defs(num);
  num = INST_accel_ctrl_tLen.dump_VCD_defs(num);
  num = INST_accel_ctrl_wBase.dump_VCD_defs(num);
  num = INST_accel_wSRAM_mem.dump_VCD_defs(num);
  num = INST_accel_wSRAM_resp.dump_VCD_defs(num);
  num = INST_cycle.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbAccelerator::dump_VCD(tVCDDumpType dt,
				   unsigned int levels,
				   MOD_mkTbAccelerator &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbAccelerator::vcd_defs(tVCDDumpType dt, MOD_mkTbAccelerator &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_accel_array_pes_0_0_accum___d21) != DEF_accel_array_pes_0_0_accum___d21)
      {
	vcd_write_val(sim_hdl, num, DEF_accel_array_pes_0_0_accum___d21, 32u);
	backing.DEF_accel_array_pes_0_0_accum___d21 = DEF_accel_array_pes_0_0_accum___d21;
      }
      ++num;
      if ((backing.DEF_accel_array_pes_0_1_accum___d32) != DEF_accel_array_pes_0_1_accum___d32)
      {
	vcd_write_val(sim_hdl, num, DEF_accel_array_pes_0_1_accum___d32, 32u);
	backing.DEF_accel_array_pes_0_1_accum___d32 = DEF_accel_array_pes_0_1_accum___d32;
      }
      ++num;
      if ((backing.DEF_accel_array_pes_1_0_accum___d40) != DEF_accel_array_pes_1_0_accum___d40)
      {
	vcd_write_val(sim_hdl, num, DEF_accel_array_pes_1_0_accum___d40, 32u);
	backing.DEF_accel_array_pes_1_0_accum___d40 = DEF_accel_array_pes_1_0_accum___d40;
      }
      ++num;
      if ((backing.DEF_b__h3447) != DEF_b__h3447)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h3447, 2u);
	backing.DEF_b__h3447 = DEF_b__h3447;
      }
      ++num;
      if ((backing.DEF_b__h4310) != DEF_b__h4310)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h4310, 32u);
	backing.DEF_b__h4310 = DEF_b__h4310;
      }
      ++num;
      if ((backing.DEF_b__h6314) != DEF_b__h6314)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h6314, 8u);
	backing.DEF_b__h6314 = DEF_b__h6314;
      }
      ++num;
      if ((backing.DEF_unsigned_cycle_0___d74) != DEF_unsigned_cycle_0___d74)
      {
	vcd_write_val(sim_hdl, num, DEF_unsigned_cycle_0___d74, 8u);
	backing.DEF_unsigned_cycle_0___d74 = DEF_unsigned_cycle_0___d74;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_accel_array_pes_0_0_accum___d21, 32u);
      backing.DEF_accel_array_pes_0_0_accum___d21 = DEF_accel_array_pes_0_0_accum___d21;
      vcd_write_val(sim_hdl, num++, DEF_accel_array_pes_0_1_accum___d32, 32u);
      backing.DEF_accel_array_pes_0_1_accum___d32 = DEF_accel_array_pes_0_1_accum___d32;
      vcd_write_val(sim_hdl, num++, DEF_accel_array_pes_1_0_accum___d40, 32u);
      backing.DEF_accel_array_pes_1_0_accum___d40 = DEF_accel_array_pes_1_0_accum___d40;
      vcd_write_val(sim_hdl, num++, DEF_b__h3447, 2u);
      backing.DEF_b__h3447 = DEF_b__h3447;
      vcd_write_val(sim_hdl, num++, DEF_b__h4310, 32u);
      backing.DEF_b__h4310 = DEF_b__h4310;
      vcd_write_val(sim_hdl, num++, DEF_b__h6314, 8u);
      backing.DEF_b__h6314 = DEF_b__h6314;
      vcd_write_val(sim_hdl, num++, DEF_unsigned_cycle_0___d74, 8u);
      backing.DEF_unsigned_cycle_0___d74 = DEF_unsigned_cycle_0___d74;
    }
}

void MOD_mkTbAccelerator::vcd_prims(tVCDDumpType dt, MOD_mkTbAccelerator &backing)
{
  INST_accel_aSRAM_mem.dump_VCD(dt, backing.INST_accel_aSRAM_mem);
  INST_accel_aSRAM_resp.dump_VCD(dt, backing.INST_accel_aSRAM_resp);
  INST_accel_array_pes_0_0_accum.dump_VCD(dt, backing.INST_accel_array_pes_0_0_accum);
  INST_accel_array_pes_0_0_act_pass.dump_VCD(dt, backing.INST_accel_array_pes_0_0_act_pass);
  INST_accel_array_pes_0_0_weight.dump_VCD(dt, backing.INST_accel_array_pes_0_0_weight);
  INST_accel_array_pes_0_1_accum.dump_VCD(dt, backing.INST_accel_array_pes_0_1_accum);
  INST_accel_array_pes_0_1_act_pass.dump_VCD(dt, backing.INST_accel_array_pes_0_1_act_pass);
  INST_accel_array_pes_0_1_weight.dump_VCD(dt, backing.INST_accel_array_pes_0_1_weight);
  INST_accel_array_pes_1_0_accum.dump_VCD(dt, backing.INST_accel_array_pes_1_0_accum);
  INST_accel_array_pes_1_0_act_pass.dump_VCD(dt, backing.INST_accel_array_pes_1_0_act_pass);
  INST_accel_array_pes_1_0_weight.dump_VCD(dt, backing.INST_accel_array_pes_1_0_weight);
  INST_accel_array_pes_1_1_accum.dump_VCD(dt, backing.INST_accel_array_pes_1_1_accum);
  INST_accel_array_pes_1_1_act_pass.dump_VCD(dt, backing.INST_accel_array_pes_1_1_act_pass);
  INST_accel_array_pes_1_1_weight.dump_VCD(dt, backing.INST_accel_array_pes_1_1_weight);
  INST_accel_ctrl_aBase.dump_VCD(dt, backing.INST_accel_ctrl_aBase);
  INST_accel_ctrl_actIdx.dump_VCD(dt, backing.INST_accel_ctrl_actIdx);
  INST_accel_ctrl_cstate.dump_VCD(dt, backing.INST_accel_ctrl_cstate);
  INST_accel_ctrl_firstActRead.dump_VCD(dt, backing.INST_accel_ctrl_firstActRead);
  INST_accel_ctrl_outputBuf.dump_VCD(dt, backing.INST_accel_ctrl_outputBuf);
  INST_accel_ctrl_streamCycle.dump_VCD(dt, backing.INST_accel_ctrl_streamCycle);
  INST_accel_ctrl_tLen.dump_VCD(dt, backing.INST_accel_ctrl_tLen);
  INST_accel_ctrl_wBase.dump_VCD(dt, backing.INST_accel_ctrl_wBase);
  INST_accel_wSRAM_mem.dump_VCD(dt, backing.INST_accel_wSRAM_mem);
  INST_accel_wSRAM_resp.dump_VCD(dt, backing.INST_accel_wSRAM_resp);
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
}
