/*
 * Generated by Bluespec Compiler
 * 
 */

/* Generation options: */
#ifndef __mkTbAccelerator_h__
#define __mkTbAccelerator_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbAccelerator module */
class MOD_mkTbAccelerator : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_RegFile<tUInt8,tUInt32> INST_accel_aSRAM_mem;
  MOD_Reg<tUInt32> INST_accel_aSRAM_resp;
  MOD_Reg<tUInt32> INST_accel_array_pes_0_0_accum;
  MOD_Reg<tUInt8> INST_accel_array_pes_0_0_act_pass;
  MOD_Reg<tUInt8> INST_accel_array_pes_0_0_weight;
  MOD_Reg<tUInt32> INST_accel_array_pes_0_1_accum;
  MOD_Reg<tUInt8> INST_accel_array_pes_0_1_act_pass;
  MOD_Reg<tUInt8> INST_accel_array_pes_0_1_weight;
  MOD_Reg<tUInt32> INST_accel_array_pes_1_0_accum;
  MOD_Reg<tUInt8> INST_accel_array_pes_1_0_act_pass;
  MOD_Reg<tUInt8> INST_accel_array_pes_1_0_weight;
  MOD_Reg<tUInt32> INST_accel_array_pes_1_1_accum;
  MOD_Reg<tUInt8> INST_accel_array_pes_1_1_act_pass;
  MOD_Reg<tUInt8> INST_accel_array_pes_1_1_weight;
  MOD_Reg<tUInt8> INST_accel_ctrl_aBase;
  MOD_Reg<tUInt8> INST_accel_ctrl_actIdx;
  MOD_Reg<tUInt8> INST_accel_ctrl_cstate;
  MOD_Reg<tUInt8> INST_accel_ctrl_firstActRead;
  MOD_Reg<tUInt64> INST_accel_ctrl_outputBuf;
  MOD_Reg<tUInt32> INST_accel_ctrl_streamCycle;
  MOD_Reg<tUInt8> INST_accel_ctrl_tLen;
  MOD_Reg<tUInt8> INST_accel_ctrl_wBase;
  MOD_RegFile<tUInt8,tUInt32> INST_accel_wSRAM_mem;
  MOD_Reg<tUInt32> INST_accel_wSRAM_resp;
  MOD_Reg<tUInt8> INST_cycle;
 
 /* Constructor */
 public:
  MOD_mkTbAccelerator(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_b__h6314;
 
 /* Local definitions */
 private:
  tUInt8 DEF_unsigned_cycle_0___d74;
  tUInt32 DEF_b__h4310;
  tUInt32 DEF_accel_array_pes_1_0_accum___d40;
  tUInt32 DEF_accel_array_pes_0_1_accum___d32;
  tUInt32 DEF_accel_array_pes_0_0_accum___d21;
  tUInt8 DEF_b__h3447;
 
 /* Rules */
 public:
  void RL_accel_ctrl_do_load_weights();
  void RL_accel_ctrl_do_load_weights_resp();
  void RL_accel_ctrl_do_stream();
  void RL_accel_ctrl_do_drain();
  void RL_count_cycles();
  void RL_load_weights();
  void RL_load_acts();
  void RL_start();
  void RL_wait_done();
  void RL_check_done();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbAccelerator &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbAccelerator &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbAccelerator &backing);
};

#endif /* ifndef __mkTbAccelerator_h__ */
