/*
 * Generated by Bluespec Compiler
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbSystolicArray.h"


/* String declarations */
static std::string const __str_literal_4("Cycle %0d: fed [0, 0] to propagate", 34u);
static std::string const __str_literal_3("Cycle %0d: fed [5, 6]", 21u);
static std::string const __str_literal_5("Cycle %0d: results = [%0d, %0d]", 31u);
static std::string const __str_literal_2("Cycle %0d: weights loaded", 25u);
static std::string const __str_literal_7("FAIL: expected [23, 34]", 23u);
static std::string const __str_literal_1("FAIL: test timed out", 20u);
static std::string const __str_literal_6("PASS: 2x2 matrix-vector multiply correct", 40u);


/* Constructor */
MOD_mkTbSystolicArray::MOD_mkTbSystolicArray(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_arr_pes_0_0_accum(simHdl, "arr_pes_0_0_accum", this, 32u, 0u, (tUInt8)0u),
    INST_arr_pes_0_0_act_pass(simHdl, "arr_pes_0_0_act_pass", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_0_0_weight(simHdl, "arr_pes_0_0_weight", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_0_1_accum(simHdl, "arr_pes_0_1_accum", this, 32u, 0u, (tUInt8)0u),
    INST_arr_pes_0_1_act_pass(simHdl, "arr_pes_0_1_act_pass", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_0_1_weight(simHdl, "arr_pes_0_1_weight", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_1_0_accum(simHdl, "arr_pes_1_0_accum", this, 32u, 0u, (tUInt8)0u),
    INST_arr_pes_1_0_act_pass(simHdl, "arr_pes_1_0_act_pass", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_1_0_weight(simHdl, "arr_pes_1_0_weight", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_1_1_accum(simHdl, "arr_pes_1_1_accum", this, 32u, 0u, (tUInt8)0u),
    INST_arr_pes_1_1_act_pass(simHdl, "arr_pes_1_1_act_pass", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_arr_pes_1_1_weight(simHdl, "arr_pes_1_1_weight", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_cycle(simHdl, "cycle", this, 8u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 19u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbSystolicArray::init_symbols_0()
{
  init_symbol(&symbols[0u], "arr_pes_0_0_accum", SYM_MODULE, &INST_arr_pes_0_0_accum);
  init_symbol(&symbols[1u], "arr_pes_0_0_act_pass", SYM_MODULE, &INST_arr_pes_0_0_act_pass);
  init_symbol(&symbols[2u], "arr_pes_0_0_weight", SYM_MODULE, &INST_arr_pes_0_0_weight);
  init_symbol(&symbols[3u], "arr_pes_0_1_accum", SYM_MODULE, &INST_arr_pes_0_1_accum);
  init_symbol(&symbols[4u], "arr_pes_0_1_act_pass", SYM_MODULE, &INST_arr_pes_0_1_act_pass);
  init_symbol(&symbols[5u], "arr_pes_0_1_weight", SYM_MODULE, &INST_arr_pes_0_1_weight);
  init_symbol(&symbols[6u], "arr_pes_1_0_accum", SYM_MODULE, &INST_arr_pes_1_0_accum);
  init_symbol(&symbols[7u], "arr_pes_1_0_act_pass", SYM_MODULE, &INST_arr_pes_1_0_act_pass);
  init_symbol(&symbols[8u], "arr_pes_1_0_weight", SYM_MODULE, &INST_arr_pes_1_0_weight);
  init_symbol(&symbols[9u], "arr_pes_1_1_accum", SYM_MODULE, &INST_arr_pes_1_1_accum);
  init_symbol(&symbols[10u], "arr_pes_1_1_act_pass", SYM_MODULE, &INST_arr_pes_1_1_act_pass);
  init_symbol(&symbols[11u], "arr_pes_1_1_weight", SYM_MODULE, &INST_arr_pes_1_1_weight);
  init_symbol(&symbols[12u], "b__h800", SYM_DEF, &DEF_b__h800, 8u);
  init_symbol(&symbols[13u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[14u], "RL_check_results", SYM_RULE);
  init_symbol(&symbols[15u], "RL_count_cycles", SYM_RULE);
  init_symbol(&symbols[16u], "RL_feed1", SYM_RULE);
  init_symbol(&symbols[17u], "RL_feed2", SYM_RULE);
  init_symbol(&symbols[18u], "RL_load_weights", SYM_RULE);
}


/* Rule actions */

void MOD_mkTbSystolicArray::RL_count_cycles()
{
  tUInt8 DEF_cycle_PLUS_1___d2;
  tUInt8 DEF_NOT_cycle_ULE_30___d4;
  DEF_b__h800 = INST_cycle.METH_read();
  DEF_NOT_cycle_ULE_30___d4 = !(DEF_b__h800 <= (tUInt8)30u);
  DEF_cycle_PLUS_1___d2 = (tUInt8)255u & (DEF_b__h800 + (tUInt8)1u);
  INST_cycle.METH_write(DEF_cycle_PLUS_1___d2);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_cycle_ULE_30___d4)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_NOT_cycle_ULE_30___d4)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbSystolicArray::RL_load_weights()
{
  DEF_b__h800 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h800;
  INST_arr_pes_0_0_weight.METH_write((tUInt8)1u);
  INST_arr_pes_0_1_weight.METH_write((tUInt8)2u);
  INST_arr_pes_1_0_weight.METH_write((tUInt8)3u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_2, DEF_unsigned_cycle___d6);
  INST_arr_pes_1_1_weight.METH_write((tUInt8)4u);
}

void MOD_mkTbSystolicArray::RL_feed1()
{
  tUInt32 DEF_arr_pes_0_0_accum_PLUS_5_MUL_SEXT_arr_pes_0_0__ETC___d13;
  tUInt32 DEF_arr_pes_1_0_accum_2_PLUS_6_MUL_SEXT_arr_pes_1__ETC___d27;
  tUInt8 DEF_b__h1897;
  tUInt8 DEF_b__h2178;
  DEF_b__h800 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h800;
  DEF_b__h2288 = INST_arr_pes_1_1_accum.METH_read();
  DEF_arr_pes_1_0_accum___d22 = INST_arr_pes_1_0_accum.METH_read();
  DEF_arr_pes_0_1_accum___d14 = INST_arr_pes_0_1_accum.METH_read();
  DEF_b__h2319 = INST_arr_pes_1_1_weight.METH_read();
  DEF_arr_pes_0_0_accum___d8 = INST_arr_pes_0_0_accum.METH_read();
  DEF_b__h2315 = INST_arr_pes_1_0_act_pass.METH_read();
  DEF_b__h2178 = INST_arr_pes_1_0_weight.METH_read();
  DEF_b__h2038 = INST_arr_pes_0_1_weight.METH_read();
  DEF_b__h2034 = INST_arr_pes_0_0_act_pass.METH_read();
  DEF_b__h1897 = INST_arr_pes_0_0_weight.METH_read();
  DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35 = DEF_b__h2288 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
														    8u,
														    (tUInt8)(DEF_b__h2315)))) * ((tUInt64)(primSignExt32(32u,
																					 8u,
																					 (tUInt8)(DEF_b__h2319))))));
  DEF_arr_pes_1_0_accum_2_PLUS_6_MUL_SEXT_arr_pes_1__ETC___d27 = DEF_arr_pes_1_0_accum___d22 + ((tUInt32)(((tUInt64)(6u)) * ((tUInt64)(primSignExt32(32u,
																		     8u,
																		     (tUInt8)(DEF_b__h2178))))));
  DEF_arr_pes_0_0_accum_PLUS_5_MUL_SEXT_arr_pes_0_0__ETC___d13 = DEF_arr_pes_0_0_accum___d8 + ((tUInt32)(((tUInt64)(5u)) * ((tUInt64)(primSignExt32(32u,
																		    8u,
																		    (tUInt8)(DEF_b__h1897))))));
  DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21 = DEF_arr_pes_0_1_accum___d14 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
																   8u,
																   (tUInt8)(DEF_b__h2034)))) * ((tUInt64)(primSignExt32(32u,
																							8u,
																							(tUInt8)(DEF_b__h2038))))));
  INST_arr_pes_0_0_accum.METH_write(DEF_arr_pes_0_0_accum_PLUS_5_MUL_SEXT_arr_pes_0_0__ETC___d13);
  INST_arr_pes_0_0_act_pass.METH_write((tUInt8)5u);
  INST_arr_pes_0_1_accum.METH_write(DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21);
  INST_arr_pes_0_1_act_pass.METH_write(DEF_b__h2034);
  INST_arr_pes_1_0_accum.METH_write(DEF_arr_pes_1_0_accum_2_PLUS_6_MUL_SEXT_arr_pes_1__ETC___d27);
  INST_arr_pes_1_0_act_pass.METH_write((tUInt8)6u);
  INST_arr_pes_1_1_accum.METH_write(DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35);
  INST_arr_pes_1_1_act_pass.METH_write(DEF_b__h2315);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_3, DEF_unsigned_cycle___d6);
}

void MOD_mkTbSystolicArray::RL_feed2()
{
  DEF_b__h800 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h800;
  DEF_b__h2288 = INST_arr_pes_1_1_accum.METH_read();
  DEF_arr_pes_1_0_accum___d22 = INST_arr_pes_1_0_accum.METH_read();
  DEF_arr_pes_0_0_accum___d8 = INST_arr_pes_0_0_accum.METH_read();
  DEF_arr_pes_0_1_accum___d14 = INST_arr_pes_0_1_accum.METH_read();
  DEF_b__h2319 = INST_arr_pes_1_1_weight.METH_read();
  DEF_b__h2315 = INST_arr_pes_1_0_act_pass.METH_read();
  DEF_b__h2038 = INST_arr_pes_0_1_weight.METH_read();
  DEF_b__h2034 = INST_arr_pes_0_0_act_pass.METH_read();
  DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35 = DEF_b__h2288 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
														    8u,
														    (tUInt8)(DEF_b__h2315)))) * ((tUInt64)(primSignExt32(32u,
																					 8u,
																					 (tUInt8)(DEF_b__h2319))))));
  DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21 = DEF_arr_pes_0_1_accum___d14 + ((tUInt32)(((tUInt64)(primSignExt32(32u,
																   8u,
																   (tUInt8)(DEF_b__h2034)))) * ((tUInt64)(primSignExt32(32u,
																							8u,
																							(tUInt8)(DEF_b__h2038))))));
  INST_arr_pes_0_0_accum.METH_write(DEF_arr_pes_0_0_accum___d8);
  INST_arr_pes_0_0_act_pass.METH_write((tUInt8)0u);
  INST_arr_pes_0_1_accum.METH_write(DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21);
  INST_arr_pes_0_1_act_pass.METH_write(DEF_b__h2034);
  INST_arr_pes_1_0_accum.METH_write(DEF_arr_pes_1_0_accum___d22);
  INST_arr_pes_1_0_act_pass.METH_write((tUInt8)0u);
  INST_arr_pes_1_1_accum.METH_write(DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35);
  INST_arr_pes_1_1_act_pass.METH_write(DEF_b__h2315);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_4, DEF_unsigned_cycle___d6);
}

void MOD_mkTbSystolicArray::RL_check_results()
{
  tUInt8 DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d44;
  tUInt8 DEF_NOT_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_ETC___d47;
  tUInt8 DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8_0_ETC___d43;
  tUInt8 DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d42;
  tUInt32 DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8___d40;
  tUInt32 DEF_signed_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_a_ETC___d41;
  tUInt32 DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2___d38;
  tUInt32 DEF_signed_arr_pes_0_0_accum_PLUS_arr_pes_1_0_acc_ETC___d39;
  DEF_b__h800 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h800;
  DEF_b__h2288 = INST_arr_pes_1_1_accum.METH_read();
  DEF_arr_pes_1_0_accum___d22 = INST_arr_pes_1_0_accum.METH_read();
  DEF_arr_pes_0_1_accum___d14 = INST_arr_pes_0_1_accum.METH_read();
  DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8___d40 = DEF_arr_pes_0_1_accum___d14 + DEF_b__h2288;
  DEF_signed_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_a_ETC___d41 = DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8___d40;
  DEF_arr_pes_0_0_accum___d8 = INST_arr_pes_0_0_accum.METH_read();
  DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2___d38 = DEF_arr_pes_0_0_accum___d8 + DEF_arr_pes_1_0_accum___d22;
  DEF_signed_arr_pes_0_0_accum_PLUS_arr_pes_1_0_acc_ETC___d39 = DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2___d38;
  DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d42 = DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2___d38 == 23u;
  DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8_0_ETC___d43 = DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8___d40 == 34u;
  DEF_NOT_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_ETC___d47 = !DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d42 || !DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8_0_ETC___d43;
  DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d44 = DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d42 && DEF_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_accum_8_0_ETC___d43;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl,
		   this,
		   "s,8,-32,-32",
		   &__str_literal_5,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_arr_pes_0_0_accum_PLUS_arr_pes_1_0_acc_ETC___d39,
		   DEF_signed_arr_pes_0_1_accum_4_PLUS_arr_pes_1_1_a_ETC___d41);
    if (DEF_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_8_E_ETC___d44)
      dollar_display(sim_hdl, this, "s", &__str_literal_6);
    if (DEF_NOT_arr_pes_0_0_accum_PLUS_arr_pes_1_0_accum_2_ETC___d47)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    dollar_finish(sim_hdl, "32", 0u);
  }
}


/* Methods */


/* Reset routines */

void MOD_mkTbSystolicArray::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_cycle.reset_RST(ARG_rst_in);
  INST_arr_pes_1_1_weight.reset_RST(ARG_rst_in);
  INST_arr_pes_1_1_act_pass.reset_RST(ARG_rst_in);
  INST_arr_pes_1_1_accum.reset_RST(ARG_rst_in);
  INST_arr_pes_1_0_weight.reset_RST(ARG_rst_in);
  INST_arr_pes_1_0_act_pass.reset_RST(ARG_rst_in);
  INST_arr_pes_1_0_accum.reset_RST(ARG_rst_in);
  INST_arr_pes_0_1_weight.reset_RST(ARG_rst_in);
  INST_arr_pes_0_1_act_pass.reset_RST(ARG_rst_in);
  INST_arr_pes_0_1_accum.reset_RST(ARG_rst_in);
  INST_arr_pes_0_0_weight.reset_RST(ARG_rst_in);
  INST_arr_pes_0_0_act_pass.reset_RST(ARG_rst_in);
  INST_arr_pes_0_0_accum.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbSystolicArray::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbSystolicArray::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_arr_pes_0_0_accum.dump_state(indent + 2u);
  INST_arr_pes_0_0_act_pass.dump_state(indent + 2u);
  INST_arr_pes_0_0_weight.dump_state(indent + 2u);
  INST_arr_pes_0_1_accum.dump_state(indent + 2u);
  INST_arr_pes_0_1_act_pass.dump_state(indent + 2u);
  INST_arr_pes_0_1_weight.dump_state(indent + 2u);
  INST_arr_pes_1_0_accum.dump_state(indent + 2u);
  INST_arr_pes_1_0_act_pass.dump_state(indent + 2u);
  INST_arr_pes_1_0_weight.dump_state(indent + 2u);
  INST_arr_pes_1_1_accum.dump_state(indent + 2u);
  INST_arr_pes_1_1_act_pass.dump_state(indent + 2u);
  INST_arr_pes_1_1_weight.dump_state(indent + 2u);
  INST_cycle.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbSystolicArray::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 26u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "arr_pes_0_0_accum___d8", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "arr_pes_0_1_accum___d14", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "arr_pes_1_0_accum___d22", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h2034", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h2038", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h2288", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h2315", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h2319", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h800", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "unsigned_cycle___d6", 8u);
  num = INST_arr_pes_0_0_accum.dump_VCD_defs(num);
  num = INST_arr_pes_0_0_act_pass.dump_VCD_defs(num);
  num = INST_arr_pes_0_0_weight.dump_VCD_defs(num);
  num = INST_arr_pes_0_1_accum.dump_VCD_defs(num);
  num = INST_arr_pes_0_1_act_pass.dump_VCD_defs(num);
  num = INST_arr_pes_0_1_weight.dump_VCD_defs(num);
  num = INST_arr_pes_1_0_accum.dump_VCD_defs(num);
  num = INST_arr_pes_1_0_act_pass.dump_VCD_defs(num);
  num = INST_arr_pes_1_0_weight.dump_VCD_defs(num);
  num = INST_arr_pes_1_1_accum.dump_VCD_defs(num);
  num = INST_arr_pes_1_1_act_pass.dump_VCD_defs(num);
  num = INST_arr_pes_1_1_weight.dump_VCD_defs(num);
  num = INST_cycle.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbSystolicArray::dump_VCD(tVCDDumpType dt,
				     unsigned int levels,
				     MOD_mkTbSystolicArray &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbSystolicArray::vcd_defs(tVCDDumpType dt, MOD_mkTbSystolicArray &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_arr_pes_0_0_accum___d8) != DEF_arr_pes_0_0_accum___d8)
      {
	vcd_write_val(sim_hdl, num, DEF_arr_pes_0_0_accum___d8, 32u);
	backing.DEF_arr_pes_0_0_accum___d8 = DEF_arr_pes_0_0_accum___d8;
      }
      ++num;
      if ((backing.DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21) != DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21)
      {
	vcd_write_val(sim_hdl, num, DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21, 32u);
	backing.DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21 = DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21;
      }
      ++num;
      if ((backing.DEF_arr_pes_0_1_accum___d14) != DEF_arr_pes_0_1_accum___d14)
      {
	vcd_write_val(sim_hdl, num, DEF_arr_pes_0_1_accum___d14, 32u);
	backing.DEF_arr_pes_0_1_accum___d14 = DEF_arr_pes_0_1_accum___d14;
      }
      ++num;
      if ((backing.DEF_arr_pes_1_0_accum___d22) != DEF_arr_pes_1_0_accum___d22)
      {
	vcd_write_val(sim_hdl, num, DEF_arr_pes_1_0_accum___d22, 32u);
	backing.DEF_arr_pes_1_0_accum___d22 = DEF_arr_pes_1_0_accum___d22;
      }
      ++num;
      if ((backing.DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35) != DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35)
      {
	vcd_write_val(sim_hdl, num, DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35, 32u);
	backing.DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35 = DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35;
      }
      ++num;
      if ((backing.DEF_b__h2034) != DEF_b__h2034)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h2034, 8u);
	backing.DEF_b__h2034 = DEF_b__h2034;
      }
      ++num;
      if ((backing.DEF_b__h2038) != DEF_b__h2038)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h2038, 8u);
	backing.DEF_b__h2038 = DEF_b__h2038;
      }
      ++num;
      if ((backing.DEF_b__h2288) != DEF_b__h2288)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h2288, 32u);
	backing.DEF_b__h2288 = DEF_b__h2288;
      }
      ++num;
      if ((backing.DEF_b__h2315) != DEF_b__h2315)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h2315, 8u);
	backing.DEF_b__h2315 = DEF_b__h2315;
      }
      ++num;
      if ((backing.DEF_b__h2319) != DEF_b__h2319)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h2319, 8u);
	backing.DEF_b__h2319 = DEF_b__h2319;
      }
      ++num;
      if ((backing.DEF_b__h800) != DEF_b__h800)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h800, 8u);
	backing.DEF_b__h800 = DEF_b__h800;
      }
      ++num;
      if ((backing.DEF_unsigned_cycle___d6) != DEF_unsigned_cycle___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_unsigned_cycle___d6, 8u);
	backing.DEF_unsigned_cycle___d6 = DEF_unsigned_cycle___d6;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_arr_pes_0_0_accum___d8, 32u);
      backing.DEF_arr_pes_0_0_accum___d8 = DEF_arr_pes_0_0_accum___d8;
      vcd_write_val(sim_hdl, num++, DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21, 32u);
      backing.DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21 = DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21;
      vcd_write_val(sim_hdl, num++, DEF_arr_pes_0_1_accum___d14, 32u);
      backing.DEF_arr_pes_0_1_accum___d14 = DEF_arr_pes_0_1_accum___d14;
      vcd_write_val(sim_hdl, num++, DEF_arr_pes_1_0_accum___d22, 32u);
      backing.DEF_arr_pes_1_0_accum___d22 = DEF_arr_pes_1_0_accum___d22;
      vcd_write_val(sim_hdl, num++, DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35, 32u);
      backing.DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35 = DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35;
      vcd_write_val(sim_hdl, num++, DEF_b__h2034, 8u);
      backing.DEF_b__h2034 = DEF_b__h2034;
      vcd_write_val(sim_hdl, num++, DEF_b__h2038, 8u);
      backing.DEF_b__h2038 = DEF_b__h2038;
      vcd_write_val(sim_hdl, num++, DEF_b__h2288, 32u);
      backing.DEF_b__h2288 = DEF_b__h2288;
      vcd_write_val(sim_hdl, num++, DEF_b__h2315, 8u);
      backing.DEF_b__h2315 = DEF_b__h2315;
      vcd_write_val(sim_hdl, num++, DEF_b__h2319, 8u);
      backing.DEF_b__h2319 = DEF_b__h2319;
      vcd_write_val(sim_hdl, num++, DEF_b__h800, 8u);
      backing.DEF_b__h800 = DEF_b__h800;
      vcd_write_val(sim_hdl, num++, DEF_unsigned_cycle___d6, 8u);
      backing.DEF_unsigned_cycle___d6 = DEF_unsigned_cycle___d6;
    }
}

void MOD_mkTbSystolicArray::vcd_prims(tVCDDumpType dt, MOD_mkTbSystolicArray &backing)
{
  INST_arr_pes_0_0_accum.dump_VCD(dt, backing.INST_arr_pes_0_0_accum);
  INST_arr_pes_0_0_act_pass.dump_VCD(dt, backing.INST_arr_pes_0_0_act_pass);
  INST_arr_pes_0_0_weight.dump_VCD(dt, backing.INST_arr_pes_0_0_weight);
  INST_arr_pes_0_1_accum.dump_VCD(dt, backing.INST_arr_pes_0_1_accum);
  INST_arr_pes_0_1_act_pass.dump_VCD(dt, backing.INST_arr_pes_0_1_act_pass);
  INST_arr_pes_0_1_weight.dump_VCD(dt, backing.INST_arr_pes_0_1_weight);
  INST_arr_pes_1_0_accum.dump_VCD(dt, backing.INST_arr_pes_1_0_accum);
  INST_arr_pes_1_0_act_pass.dump_VCD(dt, backing.INST_arr_pes_1_0_act_pass);
  INST_arr_pes_1_0_weight.dump_VCD(dt, backing.INST_arr_pes_1_0_weight);
  INST_arr_pes_1_1_accum.dump_VCD(dt, backing.INST_arr_pes_1_1_accum);
  INST_arr_pes_1_1_act_pass.dump_VCD(dt, backing.INST_arr_pes_1_1_act_pass);
  INST_arr_pes_1_1_weight.dump_VCD(dt, backing.INST_arr_pes_1_1_weight);
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
}
