/*
 * Generated by Bluespec Compiler
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbPE.h"


/* String declarations */
static std::string const __str_literal_12("Cycle %0d: accum = %0d (expect -40)", 35u);
static std::string const __str_literal_6("Cycle %0d: accum = %0d (expect 9)", 33u);
static std::string const __str_literal_9("Cycle %0d: accum after clear = %0d (expect 0)", 45u);
static std::string const __str_literal_8("Cycle %0d: clearAccum", 21u);
static std::string const __str_literal_4("Cycle %0d: feedActivation(-2), accum = %0d (expect 15)",
					 54u);
static std::string const __str_literal_11("Cycle %0d: feedActivation(10)", 29u);
static std::string const __str_literal_3("Cycle %0d: feedActivation(5), accum before = %0d", 48u);
static std::string const __str_literal_10("Cycle %0d: loadWeight(-4)", 25u);
static std::string const __str_literal_2("Cycle %0d: loadWeight(3)", 24u);
static std::string const __str_literal_7("Cycle %0d: passActivation = %0d (expect -2)", 43u);
static std::string const __str_literal_5("Cycle %0d: passActivation = %0d (expect 5)", 42u);
static std::string const __str_literal_1("FAIL: test timed out", 20u);
static std::string const __str_literal_13("PASS", 4u);


/* Constructor */
MOD_mkTbPE::MOD_mkTbPE(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_cycle(simHdl, "cycle", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_pe_accum(simHdl, "pe_accum", this, 32u, 0u, (tUInt8)0u),
    INST_pe_act_pass(simHdl, "pe_act_pass", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_pe_weight(simHdl, "pe_weight", this, 8u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 15u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbPE::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h229", SYM_DEF, &DEF_b__h229, 8u);
  init_symbol(&symbols[1u], "cycle", SYM_MODULE, &INST_cycle);
  init_symbol(&symbols[2u], "pe_accum", SYM_MODULE, &INST_pe_accum);
  init_symbol(&symbols[3u], "pe_act_pass", SYM_MODULE, &INST_pe_act_pass);
  init_symbol(&symbols[4u], "pe_weight", SYM_MODULE, &INST_pe_weight);
  init_symbol(&symbols[5u], "RL_check3", SYM_RULE);
  init_symbol(&symbols[6u], "RL_check_clear", SYM_RULE);
  init_symbol(&symbols[7u], "RL_check_neg", SYM_RULE);
  init_symbol(&symbols[8u], "RL_clear", SYM_RULE);
  init_symbol(&symbols[9u], "RL_count_cycles", SYM_RULE);
  init_symbol(&symbols[10u], "RL_feed1", SYM_RULE);
  init_symbol(&symbols[11u], "RL_feed2", SYM_RULE);
  init_symbol(&symbols[12u], "RL_feed_neg", SYM_RULE);
  init_symbol(&symbols[13u], "RL_load_neg_weight", SYM_RULE);
  init_symbol(&symbols[14u], "RL_load_weight", SYM_RULE);
}


/* Rule actions */

void MOD_mkTbPE::RL_count_cycles()
{
  tUInt8 DEF_cycle_PLUS_1___d2;
  tUInt8 DEF_NOT_cycle_ULE_20___d4;
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_NOT_cycle_ULE_20___d4 = !(DEF_b__h229 <= (tUInt8)20u);
  DEF_cycle_PLUS_1___d2 = (tUInt8)255u & (DEF_b__h229 + (tUInt8)1u);
  INST_cycle.METH_write(DEF_cycle_PLUS_1___d2);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_cycle_ULE_20___d4)
      dollar_display(sim_hdl, this, "s", &__str_literal_1);
    if (DEF_NOT_cycle_ULE_20___d4)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbPE::RL_load_weight()
{
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  INST_pe_weight.METH_write((tUInt8)3u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_2, DEF_unsigned_cycle___d6);
}

void MOD_mkTbPE::RL_feed1()
{
  tUInt32 DEF_pe_accum_PLUS_5_MUL_SEXT_pe_weight__0_1_BITS_3_ETC___d13;
  DEF_b__h384 = INST_pe_accum.METH_read();
  DEF_signed_pe_accum___d14 = DEF_b__h384;
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  DEF_b__h396 = INST_pe_weight.METH_read();
  DEF_SEXT_pe_weight____d10 = primSignExt32(32u, 8u, (tUInt8)(DEF_b__h396));
  DEF_pe_accum_PLUS_5_MUL_SEXT_pe_weight__0_1_BITS_3_ETC___d13 = DEF_b__h384 + ((tUInt32)(((tUInt64)(5u)) * ((tUInt64)(DEF_SEXT_pe_weight____d10))));
  INST_pe_accum.METH_write(DEF_pe_accum_PLUS_5_MUL_SEXT_pe_weight__0_1_BITS_3_ETC___d13);
  INST_pe_act_pass.METH_write((tUInt8)5u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,8,-32",
		   &__str_literal_3,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_accum___d14);
}

void MOD_mkTbPE::RL_feed2()
{
  tUInt32 DEF_pe_accum_PLUS_4294967294_MUL_SEXT_pe_weight__0_ETC___d18;
  DEF_b__h384 = INST_pe_accum.METH_read();
  DEF_signed_pe_accum___d14 = DEF_b__h384;
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  DEF_b__h565 = INST_pe_act_pass.METH_read();
  DEF_signed_pe_act_pass_9___d20 = DEF_b__h565;
  DEF_b__h396 = INST_pe_weight.METH_read();
  DEF_SEXT_pe_weight____d10 = primSignExt32(32u, 8u, (tUInt8)(DEF_b__h396));
  DEF_pe_accum_PLUS_4294967294_MUL_SEXT_pe_weight__0_ETC___d18 = DEF_b__h384 + ((tUInt32)(((tUInt64)(4294967294u)) * ((tUInt64)(DEF_SEXT_pe_weight____d10))));
  INST_pe_accum.METH_write(DEF_pe_accum_PLUS_4294967294_MUL_SEXT_pe_weight__0_ETC___d18);
  INST_pe_act_pass.METH_write((tUInt8)254u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl,
		   this,
		   "s,8,-32",
		   &__str_literal_4,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_accum___d14);
    dollar_display(sim_hdl,
		   this,
		   "s,8,-8",
		   &__str_literal_5,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_act_pass_9___d20);
  }
}

void MOD_mkTbPE::RL_check3()
{
  DEF_b__h384 = INST_pe_accum.METH_read();
  DEF_signed_pe_accum___d14 = DEF_b__h384;
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  DEF_b__h565 = INST_pe_act_pass.METH_read();
  DEF_signed_pe_act_pass_9___d20 = DEF_b__h565;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl,
		   this,
		   "s,8,-32",
		   &__str_literal_6,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_accum___d14);
    dollar_display(sim_hdl,
		   this,
		   "s,8,-8",
		   &__str_literal_7,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_act_pass_9___d20);
  }
}

void MOD_mkTbPE::RL_clear()
{
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  INST_pe_accum.METH_write(0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_8, DEF_unsigned_cycle___d6);
}

void MOD_mkTbPE::RL_check_clear()
{
  DEF_b__h384 = INST_pe_accum.METH_read();
  DEF_signed_pe_accum___d14 = DEF_b__h384;
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,8,-32",
		   &__str_literal_9,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_accum___d14);
}

void MOD_mkTbPE::RL_load_neg_weight()
{
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  INST_pe_weight.METH_write((tUInt8)252u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_10, DEF_unsigned_cycle___d6);
}

void MOD_mkTbPE::RL_feed_neg()
{
  tUInt32 DEF_pe_accum_PLUS_10_MUL_SEXT_pe_weight__0_6_BITS__ETC___d28;
  DEF_b__h384 = INST_pe_accum.METH_read();
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  DEF_b__h396 = INST_pe_weight.METH_read();
  DEF_SEXT_pe_weight____d10 = primSignExt32(32u, 8u, (tUInt8)(DEF_b__h396));
  DEF_pe_accum_PLUS_10_MUL_SEXT_pe_weight__0_6_BITS__ETC___d28 = DEF_b__h384 + ((tUInt32)(((tUInt64)(10u)) * ((tUInt64)(DEF_SEXT_pe_weight____d10))));
  INST_pe_accum.METH_write(DEF_pe_accum_PLUS_10_MUL_SEXT_pe_weight__0_6_BITS__ETC___d28);
  INST_pe_act_pass.METH_write((tUInt8)10u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_11, DEF_unsigned_cycle___d6);
}

void MOD_mkTbPE::RL_check_neg()
{
  DEF_b__h384 = INST_pe_accum.METH_read();
  DEF_signed_pe_accum___d14 = DEF_b__h384;
  DEF_b__h229 = INST_cycle.METH_read();
  DEF_unsigned_cycle___d6 = DEF_b__h229;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl,
		   this,
		   "s,8,-32",
		   &__str_literal_12,
		   DEF_unsigned_cycle___d6,
		   DEF_signed_pe_accum___d14);
    dollar_display(sim_hdl, this, "s", &__str_literal_13);
    dollar_finish(sim_hdl, "32", 0u);
  }
}


/* Methods */


/* Reset routines */

void MOD_mkTbPE::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_pe_weight.reset_RST(ARG_rst_in);
  INST_pe_act_pass.reset_RST(ARG_rst_in);
  INST_pe_accum.reset_RST(ARG_rst_in);
  INST_cycle.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbPE::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbPE::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_cycle.dump_state(indent + 2u);
  INST_pe_accum.dump_state(indent + 2u);
  INST_pe_act_pass.dump_state(indent + 2u);
  INST_pe_weight.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbPE::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 13u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "SEXT_pe_weight____d10", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h229", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h384", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h396", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h565", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "signed_pe_accum___d14", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "signed_pe_act_pass_9___d20", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "unsigned_cycle___d6", 8u);
  num = INST_cycle.dump_VCD_defs(num);
  num = INST_pe_accum.dump_VCD_defs(num);
  num = INST_pe_act_pass.dump_VCD_defs(num);
  num = INST_pe_weight.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbPE::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbPE &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbPE::vcd_defs(tVCDDumpType dt, MOD_mkTbPE &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_SEXT_pe_weight____d10) != DEF_SEXT_pe_weight____d10)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_pe_weight____d10, 32u);
	backing.DEF_SEXT_pe_weight____d10 = DEF_SEXT_pe_weight____d10;
      }
      ++num;
      if ((backing.DEF_b__h229) != DEF_b__h229)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h229, 8u);
	backing.DEF_b__h229 = DEF_b__h229;
      }
      ++num;
      if ((backing.DEF_b__h384) != DEF_b__h384)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h384, 32u);
	backing.DEF_b__h384 = DEF_b__h384;
      }
      ++num;
      if ((backing.DEF_b__h396) != DEF_b__h396)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h396, 8u);
	backing.DEF_b__h396 = DEF_b__h396;
      }
      ++num;
      if ((backing.DEF_b__h565) != DEF_b__h565)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h565, 8u);
	backing.DEF_b__h565 = DEF_b__h565;
      }
      ++num;
      if ((backing.DEF_signed_pe_accum___d14) != DEF_signed_pe_accum___d14)
      {
	vcd_write_val(sim_hdl, num, DEF_signed_pe_accum___d14, 32u);
	backing.DEF_signed_pe_accum___d14 = DEF_signed_pe_accum___d14;
      }
      ++num;
      if ((backing.DEF_signed_pe_act_pass_9___d20) != DEF_signed_pe_act_pass_9___d20)
      {
	vcd_write_val(sim_hdl, num, DEF_signed_pe_act_pass_9___d20, 8u);
	backing.DEF_signed_pe_act_pass_9___d20 = DEF_signed_pe_act_pass_9___d20;
      }
      ++num;
      if ((backing.DEF_unsigned_cycle___d6) != DEF_unsigned_cycle___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_unsigned_cycle___d6, 8u);
	backing.DEF_unsigned_cycle___d6 = DEF_unsigned_cycle___d6;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_pe_weight____d10, 32u);
      backing.DEF_SEXT_pe_weight____d10 = DEF_SEXT_pe_weight____d10;
      vcd_write_val(sim_hdl, num++, DEF_b__h229, 8u);
      backing.DEF_b__h229 = DEF_b__h229;
      vcd_write_val(sim_hdl, num++, DEF_b__h384, 32u);
      backing.DEF_b__h384 = DEF_b__h384;
      vcd_write_val(sim_hdl, num++, DEF_b__h396, 8u);
      backing.DEF_b__h396 = DEF_b__h396;
      vcd_write_val(sim_hdl, num++, DEF_b__h565, 8u);
      backing.DEF_b__h565 = DEF_b__h565;
      vcd_write_val(sim_hdl, num++, DEF_signed_pe_accum___d14, 32u);
      backing.DEF_signed_pe_accum___d14 = DEF_signed_pe_accum___d14;
      vcd_write_val(sim_hdl, num++, DEF_signed_pe_act_pass_9___d20, 8u);
      backing.DEF_signed_pe_act_pass_9___d20 = DEF_signed_pe_act_pass_9___d20;
      vcd_write_val(sim_hdl, num++, DEF_unsigned_cycle___d6, 8u);
      backing.DEF_unsigned_cycle___d6 = DEF_unsigned_cycle___d6;
    }
}

void MOD_mkTbPE::vcd_prims(tVCDDumpType dt, MOD_mkTbPE &backing)
{
  INST_cycle.dump_VCD(dt, backing.INST_cycle);
  INST_pe_accum.dump_VCD(dt, backing.INST_pe_accum);
  INST_pe_act_pass.dump_VCD(dt, backing.INST_pe_act_pass);
  INST_pe_weight.dump_VCD(dt, backing.INST_pe_weight);
}
