/*
 * Generated by Bluespec Compiler
 * 
 */

/* Generation options: */
#ifndef __mkTbPE_h__
#define __mkTbPE_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbPE module */
class MOD_mkTbPE : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_cycle;
  MOD_Reg<tUInt32> INST_pe_accum;
  MOD_Reg<tUInt8> INST_pe_act_pass;
  MOD_Reg<tUInt8> INST_pe_weight;
 
 /* Constructor */
 public:
  MOD_mkTbPE(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_b__h229;
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_pe_accum___d14;
  tUInt32 DEF_b__h384;
  tUInt8 DEF_unsigned_cycle___d6;
  tUInt8 DEF_signed_pe_act_pass_9___d20;
  tUInt8 DEF_b__h565;
  tUInt8 DEF_b__h396;
  tUInt32 DEF_SEXT_pe_weight____d10;
 
 /* Rules */
 public:
  void RL_count_cycles();
  void RL_load_weight();
  void RL_feed1();
  void RL_feed2();
  void RL_check3();
  void RL_clear();
  void RL_check_clear();
  void RL_load_neg_weight();
  void RL_feed_neg();
  void RL_check_neg();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbPE &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbPE &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbPE &backing);
};

#endif /* ifndef __mkTbPE_h__ */
