/*
 * Generated by Bluespec Compiler
 * 
 */

/* Generation options: */
#ifndef __mkTbSystolicArray_h__
#define __mkTbSystolicArray_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbSystolicArray module */
class MOD_mkTbSystolicArray : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_arr_pes_0_0_accum;
  MOD_Reg<tUInt8> INST_arr_pes_0_0_act_pass;
  MOD_Reg<tUInt8> INST_arr_pes_0_0_weight;
  MOD_Reg<tUInt32> INST_arr_pes_0_1_accum;
  MOD_Reg<tUInt8> INST_arr_pes_0_1_act_pass;
  MOD_Reg<tUInt8> INST_arr_pes_0_1_weight;
  MOD_Reg<tUInt32> INST_arr_pes_1_0_accum;
  MOD_Reg<tUInt8> INST_arr_pes_1_0_act_pass;
  MOD_Reg<tUInt8> INST_arr_pes_1_0_weight;
  MOD_Reg<tUInt32> INST_arr_pes_1_1_accum;
  MOD_Reg<tUInt8> INST_arr_pes_1_1_act_pass;
  MOD_Reg<tUInt8> INST_arr_pes_1_1_weight;
  MOD_Reg<tUInt8> INST_cycle;
 
 /* Constructor */
 public:
  MOD_mkTbSystolicArray(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_b__h800;
 
 /* Local definitions */
 private:
  tUInt8 DEF_unsigned_cycle___d6;
  tUInt32 DEF_b__h2288;
  tUInt32 DEF_arr_pes_1_0_accum___d22;
  tUInt32 DEF_arr_pes_0_1_accum___d14;
  tUInt32 DEF_arr_pes_0_0_accum___d8;
  tUInt8 DEF_b__h2319;
  tUInt8 DEF_b__h2315;
  tUInt8 DEF_b__h2038;
  tUInt8 DEF_b__h2034;
  tUInt32 DEF_arr_pes_1_1_accum_8_PLUS_SEXT_arr_pes_1_0_act__ETC___d35;
  tUInt32 DEF_arr_pes_0_1_accum_4_PLUS_SEXT_arr_pes_0_0_act__ETC___d21;
 
 /* Rules */
 public:
  void RL_count_cycles();
  void RL_load_weights();
  void RL_feed1();
  void RL_feed2();
  void RL_check_results();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbSystolicArray &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbSystolicArray &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbSystolicArray &backing);
};

#endif /* ifndef __mkTbSystolicArray_h__ */
