/*
 * Generated by Bluespec Compiler
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbAccelerator.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbAccelerator::MODEL_mkTbAccelerator()
{
  mkTbAccelerator_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbAccelerator()
{
  MODEL_mkTbAccelerator *model = new MODEL_mkTbAccelerator();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbAccelerator &INST_top = *((MOD_mkTbAccelerator *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_NOT_cycle_0_ULE_2_0___d81;
	 tUInt8 DEF_INST_top_DEF_accel_ctrl_cstate_EQ_5___d82;
	 tUInt8 DEF_INST_top_DEF_accel_ctrl_cstate__h1448;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_load_weights;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_load_weights;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_load_weights_resp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_load_weights_resp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_stream;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_stream;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_drain;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_drain;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_load_weights;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_load_weights;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_load_acts;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_load_acts;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_wait_done;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_wait_done;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_check_done;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_check_done;
	 DEF_INST_top_DEF_accel_ctrl_cstate__h1448 = INST_top.INST_accel_ctrl_cstate.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_drain = DEF_INST_top_DEF_accel_ctrl_cstate__h1448 == (tUInt8)4u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_drain = DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_drain;
	 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_load_weights = DEF_INST_top_DEF_accel_ctrl_cstate__h1448 == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_load_weights = DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_load_weights;
	 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_load_weights_resp = DEF_INST_top_DEF_accel_ctrl_cstate__h1448 == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_load_weights_resp = DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_load_weights_resp;
	 DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_stream = DEF_INST_top_DEF_accel_ctrl_cstate__h1448 == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_stream = DEF_INST_top_DEF_CAN_FIRE_RL_accel_ctrl_do_stream;
	 INST_top.DEF_b__h6314 = INST_top.INST_cycle.METH_read();
	 DEF_INST_top_DEF_accel_ctrl_cstate_EQ_5___d82 = DEF_INST_top_DEF_accel_ctrl_cstate__h1448 == (tUInt8)5u;
	 DEF_INST_top_DEF_NOT_cycle_0_ULE_2_0___d81 = !((INST_top.DEF_b__h6314) <= (tUInt8)2u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_check_done = DEF_INST_top_DEF_accel_ctrl_cstate_EQ_5___d82 && DEF_INST_top_DEF_NOT_cycle_0_ULE_2_0___d81;
	 DEF_INST_top_DEF_WILL_FIRE_RL_check_done = DEF_INST_top_DEF_CAN_FIRE_RL_check_done;
	 DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles = DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles;
	 DEF_INST_top_DEF_CAN_FIRE_RL_load_acts = (INST_top.DEF_b__h6314) == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_load_acts = DEF_INST_top_DEF_CAN_FIRE_RL_load_acts;
	 DEF_INST_top_DEF_CAN_FIRE_RL_load_weights = (INST_top.DEF_b__h6314) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_load_weights = DEF_INST_top_DEF_CAN_FIRE_RL_load_weights;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start = DEF_INST_top_DEF_accel_ctrl_cstate__h1448 == (tUInt8)0u && (INST_top.DEF_b__h6314) == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start = DEF_INST_top_DEF_CAN_FIRE_RL_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_wait_done = DEF_INST_top_DEF_NOT_cycle_0_ULE_2_0___d81 && !DEF_INST_top_DEF_accel_ctrl_cstate_EQ_5___d82;
	 DEF_INST_top_DEF_WILL_FIRE_RL_wait_done = DEF_INST_top_DEF_CAN_FIRE_RL_wait_done;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_check_done)
	   INST_top.RL_check_done();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start)
	   INST_top.RL_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_wait_done)
	   INST_top.RL_wait_done();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_drain)
	   INST_top.RL_accel_ctrl_do_drain();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_load_weights)
	   INST_top.RL_accel_ctrl_do_load_weights();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_load_weights_resp)
	   INST_top.RL_accel_ctrl_do_load_weights_resp();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_accel_ctrl_do_stream)
	   INST_top.RL_accel_ctrl_do_stream();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_load_acts)
	   INST_top.RL_load_acts();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_load_weights)
	   INST_top.RL_load_weights();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles)
	   INST_top.RL_count_cycles();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_accel_array_pes_0_0_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_0_0_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_0_0_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_0_1_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_0_1_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_0_1_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_1_0_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_1_0_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_1_0_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_1_1_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_1_1_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_array_pes_1_1_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_cstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_wBase.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_aBase.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_tLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_actIdx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_streamCycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_accel_ctrl_firstActRead.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbAccelerator::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbAccelerator_instance = new MOD_mkTbAccelerator(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbAccelerator_instance->set_clk_0)("CLK");
}
void MODEL_mkTbAccelerator::destroy_model()
{
  delete mkTbAccelerator_instance;
  mkTbAccelerator_instance = NULL;
}
void MODEL_mkTbAccelerator::reset_model(bool asserted)
{
  (mkTbAccelerator_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbAccelerator::get_instance()
{
  return mkTbAccelerator_instance;
}

/* Fill in version numbers */
void MODEL_mkTbAccelerator::get_version(char const **name, char const **build)
{
  *name = NULL;
  *build = NULL;
}

/* Get the model creation time */
time_t MODEL_mkTbAccelerator::get_creation_time()
{
  
  /* Thu Jan  1 00:00:00 UTC 1970 */
  return 0llu;
}

/* State dumping function */
void MODEL_mkTbAccelerator::dump_state()
{
  (mkTbAccelerator_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbAccelerator & mkTbAccelerator_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbAccelerator *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbAccelerator(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbAccelerator::dump_VCD_defs()
{
  (mkTbAccelerator_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbAccelerator::dump_VCD(tVCDDumpType dt)
{
  (mkTbAccelerator_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbAccelerator_backing(sim_hdl));
}
