/*
 * Generated by Bluespec Compiler
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbPE.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbPE::MODEL_mkTbPE()
{
  mkTbPE_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbPE()
{
  MODEL_mkTbPE *model = new MODEL_mkTbPE();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbPE &INST_top = *((MOD_mkTbPE *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_load_weight;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_load_weight;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_feed1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_feed1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_feed2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_feed2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_check3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_check3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_clear;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_clear;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_check_clear;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_check_clear;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_load_neg_weight;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_load_neg_weight;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_feed_neg;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_feed_neg;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_check_neg;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_check_neg;
	 INST_top.DEF_b__h229 = INST_top.INST_cycle.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_check3 = (INST_top.DEF_b__h229) == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_check3 = DEF_INST_top_DEF_CAN_FIRE_RL_check3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_check_clear = (INST_top.DEF_b__h229) == (tUInt8)5u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_check_clear = DEF_INST_top_DEF_CAN_FIRE_RL_check_clear;
	 DEF_INST_top_DEF_CAN_FIRE_RL_check_neg = (INST_top.DEF_b__h229) == (tUInt8)8u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_check_neg = DEF_INST_top_DEF_CAN_FIRE_RL_check_neg;
	 DEF_INST_top_DEF_CAN_FIRE_RL_clear = (INST_top.DEF_b__h229) == (tUInt8)4u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_clear = DEF_INST_top_DEF_CAN_FIRE_RL_clear;
	 DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles = DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles;
	 DEF_INST_top_DEF_CAN_FIRE_RL_feed1 = (INST_top.DEF_b__h229) == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_feed1 = DEF_INST_top_DEF_CAN_FIRE_RL_feed1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_feed2 = (INST_top.DEF_b__h229) == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_feed2 = DEF_INST_top_DEF_CAN_FIRE_RL_feed2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_feed_neg = (INST_top.DEF_b__h229) == (tUInt8)7u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_feed_neg = DEF_INST_top_DEF_CAN_FIRE_RL_feed_neg;
	 DEF_INST_top_DEF_CAN_FIRE_RL_load_neg_weight = (INST_top.DEF_b__h229) == (tUInt8)6u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_load_neg_weight = DEF_INST_top_DEF_CAN_FIRE_RL_load_neg_weight;
	 DEF_INST_top_DEF_CAN_FIRE_RL_load_weight = (INST_top.DEF_b__h229) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_load_weight = DEF_INST_top_DEF_CAN_FIRE_RL_load_weight;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_check3)
	   INST_top.RL_check3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_check_neg)
	   INST_top.RL_check_neg();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_check_clear)
	   INST_top.RL_check_clear();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_clear)
	   INST_top.RL_clear();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_feed1)
	   INST_top.RL_feed1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_feed2)
	   INST_top.RL_feed2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_feed_neg)
	   INST_top.RL_feed_neg();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_load_neg_weight)
	   INST_top.RL_load_neg_weight();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_load_weight)
	   INST_top.RL_load_weight();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles)
	   INST_top.RL_count_cycles();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_pe_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pe_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pe_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbPE::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbPE_instance = new MOD_mkTbPE(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbPE_instance->set_clk_0)("CLK");
}
void MODEL_mkTbPE::destroy_model()
{
  delete mkTbPE_instance;
  mkTbPE_instance = NULL;
}
void MODEL_mkTbPE::reset_model(bool asserted)
{
  (mkTbPE_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbPE::get_instance()
{
  return mkTbPE_instance;
}

/* Fill in version numbers */
void MODEL_mkTbPE::get_version(char const **name, char const **build)
{
  *name = NULL;
  *build = NULL;
}

/* Get the model creation time */
time_t MODEL_mkTbPE::get_creation_time()
{
  
  /* Thu Jan  1 00:00:00 UTC 1970 */
  return 0llu;
}

/* State dumping function */
void MODEL_mkTbPE::dump_state()
{
  (mkTbPE_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbPE & mkTbPE_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbPE *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbPE(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbPE::dump_VCD_defs()
{
  (mkTbPE_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbPE::dump_VCD(tVCDDumpType dt)
{
  (mkTbPE_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbPE_backing(sim_hdl));
}
