/*
 * Generated by Bluespec Compiler
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbSystolicArray.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbSystolicArray::MODEL_mkTbSystolicArray()
{
  mkTbSystolicArray_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbSystolicArray()
{
  MODEL_mkTbSystolicArray *model = new MODEL_mkTbSystolicArray();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbSystolicArray &INST_top = *((MOD_mkTbSystolicArray *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_load_weights;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_load_weights;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_feed1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_feed1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_feed2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_feed2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_check_results;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_check_results;
	 INST_top.DEF_b__h800 = INST_top.INST_cycle.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_check_results = (INST_top.DEF_b__h800) == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_check_results = DEF_INST_top_DEF_CAN_FIRE_RL_check_results;
	 DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles = DEF_INST_top_DEF_CAN_FIRE_RL_count_cycles;
	 DEF_INST_top_DEF_CAN_FIRE_RL_feed1 = (INST_top.DEF_b__h800) == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_feed1 = DEF_INST_top_DEF_CAN_FIRE_RL_feed1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_feed2 = (INST_top.DEF_b__h800) == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_feed2 = DEF_INST_top_DEF_CAN_FIRE_RL_feed2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_load_weights = (INST_top.DEF_b__h800) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_load_weights = DEF_INST_top_DEF_CAN_FIRE_RL_load_weights;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_check_results)
	   INST_top.RL_check_results();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_feed1)
	   INST_top.RL_feed1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_feed2)
	   INST_top.RL_feed2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_load_weights)
	   INST_top.RL_load_weights();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_count_cycles)
	   INST_top.RL_count_cycles();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_arr_pes_0_0_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_0_0_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_0_0_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_0_1_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_0_1_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_0_1_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_1_0_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_1_0_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_1_0_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_1_1_weight.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_1_1_accum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arr_pes_1_1_act_pass.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbSystolicArray::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbSystolicArray_instance = new MOD_mkTbSystolicArray(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbSystolicArray_instance->set_clk_0)("CLK");
}
void MODEL_mkTbSystolicArray::destroy_model()
{
  delete mkTbSystolicArray_instance;
  mkTbSystolicArray_instance = NULL;
}
void MODEL_mkTbSystolicArray::reset_model(bool asserted)
{
  (mkTbSystolicArray_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbSystolicArray::get_instance()
{
  return mkTbSystolicArray_instance;
}

/* Fill in version numbers */
void MODEL_mkTbSystolicArray::get_version(char const **name, char const **build)
{
  *name = NULL;
  *build = NULL;
}

/* Get the model creation time */
time_t MODEL_mkTbSystolicArray::get_creation_time()
{
  
  /* Thu Jan  1 00:00:00 UTC 1970 */
  return 0llu;
}

/* State dumping function */
void MODEL_mkTbSystolicArray::dump_state()
{
  (mkTbSystolicArray_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbSystolicArray & mkTbSystolicArray_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbSystolicArray *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbSystolicArray(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbSystolicArray::dump_VCD_defs()
{
  (mkTbSystolicArray_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbSystolicArray::dump_VCD(tVCDDumpType dt)
{
  (mkTbSystolicArray_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbSystolicArray_backing(sim_hdl));
}
